library verilog;
use verilog.vl_types.all;
entity DE2_115_D8M_RTL is
    port(
        CLOCK2_50       : in     vl_logic;
        CLOCK3_50       : in     vl_logic;
        CLOCK_50        : in     vl_logic;
        LEDG            : out    vl_logic_vector(8 downto 0);
        LEDR            : out    vl_logic_vector(17 downto 0);
        KEY             : in     vl_logic_vector(3 downto 0);
        SW              : in     vl_logic_vector(17 downto 0);
        HEX0            : out    vl_logic_vector(6 downto 0);
        HEX1            : out    vl_logic_vector(6 downto 0);
        HEX2            : out    vl_logic_vector(6 downto 0);
        HEX3            : out    vl_logic_vector(6 downto 0);
        HEX4            : out    vl_logic_vector(6 downto 0);
        HEX5            : out    vl_logic_vector(6 downto 0);
        HEX6            : out    vl_logic_vector(6 downto 0);
        HEX7            : out    vl_logic_vector(6 downto 0);
        VGA_BLANK_N     : out    vl_logic;
        VGA_B           : out    vl_logic_vector(7 downto 0);
        VGA_CLK         : out    vl_logic;
        VGA_G           : out    vl_logic_vector(7 downto 0);
        VGA_HS          : out    vl_logic;
        VGA_R           : out    vl_logic_vector(7 downto 0);
        VGA_SYNC_N      : out    vl_logic;
        VGA_VS          : out    vl_logic;
        DRAM_ADDR       : out    vl_logic_vector(12 downto 0);
        DRAM_BA         : out    vl_logic_vector(1 downto 0);
        DRAM_CAS_N      : out    vl_logic;
        DRAM_CKE        : out    vl_logic;
        DRAM_CLK        : out    vl_logic;
        DRAM_CS_N       : out    vl_logic;
        DRAM_DQ         : inout  vl_logic_vector(31 downto 0);
        DRAM_DQM        : out    vl_logic_vector(3 downto 0);
        DRAM_RAS_N      : out    vl_logic;
        DRAM_WE_N       : out    vl_logic;
        cmos_scl        : inout  vl_logic;
        cmos_sda        : inout  vl_logic;
        cmos_pwdn       : out    vl_logic;
        cmos_rst_n      : out    vl_logic;
        cmos_xclk       : out    vl_logic;
        cmos_pclk       : in     vl_logic;
        cmos_href       : in     vl_logic;
        cmos_vsync      : in     vl_logic;
        cmos_db         : in     vl_logic_vector(7 downto 0);
        EX_IO           : out    vl_logic_vector(6 downto 0)
    );
end DE2_115_D8M_RTL;
