/* As it shall pertain to a small portion of this design file: Copyright 2019, Grant Yu
Majority of the design file: Credits to Terasic and Terasic System Builder.
This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see [https://www.gnu.org/licenses/]. */

//=======================================================
//  This code is generated by Terasic System Builder
//=======================================================

module DE2_115_D8M_RTL (

	//////////// CLOCK //////////
	input 		          		CLOCK2_50,
	input 		          		CLOCK3_50,
	input 		          		CLOCK_50,

	//////////// LED //////////
	output		     [8:0]		LEDG,
	output		    [17:0]		LEDR,

	//////////// KEY //////////
	input 		     [3:0]		KEY,

	//////////// SW //////////
	input 		    [17:0]		SW,

	//////////// SEG7 //////////
	output		     [6:0]		HEX0,
	output		     [6:0]		HEX1,
	output		     [6:0]		HEX2,
	output		     [6:0]		HEX3,
	output		     [6:0]		HEX4,
	output		     [6:0]		HEX5,
	output		     [6:0]		HEX6,
	output		     [6:0]		HEX7,

	//////////// VGA //////////
	output		          		VGA_BLANK_N,
	output		     [7:0]		VGA_B,
	output		          		VGA_CLK,
	output		     [7:0]		VGA_G,
	output		          		VGA_HS,
	output		     [7:0]		VGA_R,
	output		          		VGA_SYNC_N,
	output		          		VGA_VS,

	//////////// SDRAM //////////
	output		    [12:0]		DRAM_ADDR,
	output		     [1:0]		DRAM_BA,
	output		          		DRAM_CAS_N,
	output		          		DRAM_CKE,
	output		          		DRAM_CLK,
	output		          		DRAM_CS_N,
	inout 		    [31:0]		DRAM_DQ,
	output		     [3:0]		DRAM_DQM,
	output		          		DRAM_RAS_N,
	output		          		DRAM_WE_N,

	//////////// GPIO connect to D8M-GPIO / OV7670 (NOMES EXATOS DO .QSF) //////////
	inout 		          		CAMERA_I2C_SCL,
	inout 		          		CAMERA_I2C_SDA,
	output		          		CAMERA_PWDN_n,
	output		          		MIPI_CS_n,
	inout 		          		MIPI_I2C_SCL,
	inout 		          		MIPI_I2C_SDA,
	output		          		MIPI_MCLK,
	input 		          		MIPI_PIXEL_CLK,
	input 		     [9:0]		MIPI_PIXEL_D,
	input 		          		MIPI_PIXEL_HS,
	input 		          		MIPI_PIXEL_VS,
	output		          		MIPI_REFCLK,
	output		          		MIPI_RESET_n,
	output		     [6:0]		EX_IO
);

//=============================================================================
// REG/WIRE declarations
//=============================================================================
wire	[15:0]	SDRAM_RD_DATA;
wire			DLY_RST_0;
wire			DLY_RST_1;
wire			DLY_RST_2;
wire			SDRAM_CTRL_CLK;
wire			D8M_CK_HZ;
wire			D8M_CK_HZ2;
wire			D8M_CK_HZ3;

wire	[7:0]	RED;
wire	[7:0]	GREEN;
wire	[7:0]	BLUE;
wire	[12:0]	VGA_H_CNT;
wire	[12:0]	VGA_V_CNT;
wire			READ_Request;
wire	[7:0]	B_AUTO;
wire	[7:0]	G_AUTO;
wire	[7:0]	R_AUTO;
wire			RESET_N;

// Sinais intermediários do processador de imagem (APPLICATION_BLOCK)
wire	[7:0]	processed_VGA_R;
wire	[7:0]	processed_VGA_G;
wire	[7:0]	processed_VGA_B;

//=======================================================
// Structural coding
//=======================================================

//------ DESATIVADO / ESTÁTICO --
assign HEX2 = 7'h7F;
assign HEX3 = 7'h7F;
assign HEX4 = 7'h7F;
assign HEX5 = 7'h7F;
assign HEX6 = 7'h7F;
assign EX_IO = 7'b0;

assign MIPI_CS_n    = 1'b0;
assign MIPI_MCLK    = 1'b0;
assign MIPI_I2C_SCL = 1'b1;
assign MIPI_I2C_SDA = 1'b1;

//------ CONTROLE DE ENERGIA E RESET DA CÂMERA OV7670 --
assign CAMERA_PWDN_n = 1'b0;     // Câmera mantida sempre ativa (0 = Ligada)
assign MIPI_RESET_n  = RESET_N;  // Reset síncrono com a placa

//----- RESET RELAY --
RESET_DELAY u2 (	
	.iRST   ( KEY[0] ),
	.iCLK   ( CLOCK2_50 ),
	.oRST_0 ( DLY_RST_0 ),
	.oRST_1 ( DLY_RST_1 ),
	.oRST_2 ( DLY_RST_2 ),
	.oREADY ( RESET_N )
);

//------ OV7670 REF CLOCK (24 MHz) --
pll_test pll_ref(
	.inclk0 ( CLOCK3_50 ),
	.areset ( ~KEY[0] ),
	.c0     ( MIPI_REFCLK ) // Fornece 24 MHz exatamente no pino PIN_AE22
);

//------ VGA REF CLOCK (25.18 MHz) --
VIDEO_PLL pll_ref1(
	.inclk0 ( CLOCK2_50 ),
	.areset ( ~KEY[0] ),
	.c0     ( VGA_CLK )     // 25.18 MHz para a varredura VGA
);

//------ SDRAM CLOCK GENERATOR (100 MHz) --
sdram_pll u6(
	.areset ( 1'b0 ),
	.inclk0 ( CLOCK_50 ),
	.c1     ( DRAM_CLK ),       // 100MHZ -90 degree
	.c0     ( SDRAM_CTRL_CLK )  // 100MHZ 0 degree
);

// Seleção do barramento de dados da câmera (SW[3] alterna entre D[7:0] e D[9:2])
wire [7:0] cmos_db_bus = (SW[3]) ? MIPI_PIXEL_D[9:2] : MIPI_PIXEL_D[7:0];

//------ INSTANCIAÇÃO DO DRIVER DA CÂMERA OV7670 ------
camera_interface camera_inst (
	.clk         ( CLOCK_50 ),        // Clock síncrono de 50MHz da FPGA
	.clk_100     ( SDRAM_CTRL_CLK ), // Clock de barramento de 100MHz
	.rst_n       ( RESET_N ),        // Reset geral síncrono da placa
	.key         ( KEY[3:0] ),       // Controle de brilho/contraste
	.cmos_pclk   ( MIPI_PIXEL_CLK ), // PCLK lido do PIN_AC15
	.cmos_href   ( MIPI_PIXEL_HS ),  // HREF lido do PIN_AG25
	.cmos_vsync  ( MIPI_PIXEL_VS ),  // VSYNC lido do PIN_AF22
	.cmos_db     ( cmos_db_bus ),    // Barramento de dados de 8 bits
	.cmos_sda    ( CAMERA_I2C_SDA ), // I2C SDA no PIN_AE24
	.cmos_scl    ( CAMERA_I2C_SCL ), // I2C SCL no PIN_AG22
	.cmos_rst_n  ( ),
	.cmos_pwdn   ( ),
	.cmos_xclk   ( ),
	.rd_en       ( 1'b0 ),
	.dout        ( ),
	.data_count_r( ),
	.led         ( )
);

//=============================================================================
// CAPTURA SÍNCRONA DE PIXELS DA OV7670
//=============================================================================

reg [9:0] line_pixel_cnt;
reg [9:0] frame_line_cnt;
reg       byte_flag;
reg [7:0] msb_byte;
reg       write_pixel_en;
reg [7:0] captured_gray;

// Detecção de borda do HREF (início/fim de linha)
reg href_d;
always @(posedge MIPI_PIXEL_CLK or negedge RESET_N) begin
	if (~RESET_N) href_d <= 1'b0;
	else href_d <= MIPI_PIXEL_HS;
end

wire href_start = MIPI_PIXEL_HS & ~href_d;

always @(posedge MIPI_PIXEL_CLK or negedge RESET_N) begin
	if (~RESET_N) begin
		line_pixel_cnt <= 10'd0;
		frame_line_cnt <= 10'd0;
		byte_flag      <= 1'b0;
		msb_byte       <= 8'h00;
		write_pixel_en <= 1'b0;
		captured_gray  <= 8'h00;
	end else if (MIPI_PIXEL_VS) begin
		line_pixel_cnt <= 10'd0;
		frame_line_cnt <= 10'd0;
		byte_flag      <= 1'b0;
		write_pixel_en <= 1'b0;
	end else if (href_start) begin
		line_pixel_cnt <= 10'd0;
		byte_flag      <= 1'b0;
		write_pixel_en <= 1'b0;
	end else if (MIPI_PIXEL_HS) begin
		if (byte_flag == 1'b0) begin
			msb_byte       <= cmos_db_bus;
			byte_flag      <= 1'b1;
			write_pixel_en <= 1'b0;
		end else begin
			byte_flag <= 1'b0;
			if (line_pixel_cnt < 10'd640 && frame_line_cnt < 10'd480) begin
				write_pixel_en <= 1'b1;
				line_pixel_cnt <= line_pixel_cnt + 1'b1;
				
				// SW[2] = 0 -> Conversão RGB565 para Grayscale
				// SW[2] = 1 -> Modo YUV422 (Byte Y)
				if (SW[2]) begin
					captured_gray <= msb_byte;
				end else begin
					captured_gray <= ({msb_byte[7:3], msb_byte[7:5]} * 306 + 
					                   {msb_byte[2:0], cmos_db_bus[7:5], msb_byte[2:1]} * 601 + 
					                   {cmos_db_bus[4:0], cmos_db_bus[4:2]} * 117) >> 10;
				end
			end else begin
				write_pixel_en <= 1'b0;
			end
		end
	end else begin
		write_pixel_en <= 1'b0;
	end
end

// SELETOR DE MODO DE TESTE AUTÔNOMO (SW[1]):
// SW[1] = 0 -> Sinal da Câmera OV7670
// SW[1] = 1 -> Padrão Sintético (VGA_CLK)
wire [7:0] final_sdram_write_gray = (SW[1]) ? VGA_H_CNT[7:0] : captured_gray;
wire       final_sdram_write_en   = (SW[1]) ? (VGA_H_CNT < 640 && VGA_V_CNT < 480) : write_pixel_en;
wire       final_sdram_write_clk  = (SW[1]) ? VGA_CLK : MIPI_PIXEL_CLK;

//------ SDRAM CONTROLLER ------
Sdram_Control u7 (
	// HOST Side
	.RESET_N      ( KEY[0] ),
	.CLK          ( SDRAM_CTRL_CLK ),
	.WR1_DATA     ( {final_sdram_write_gray, 2'b00} ),
	.WR1          ( final_sdram_write_en ),
	.WR1_ADDR     ( 0 ),
	.WR1_MAX_ADDR ( 640*480 ),
	.WR1_LENGTH   ( 256 ),
	.WR1_LOAD     ( !DLY_RST_0 ),
	.WR1_CLK      ( final_sdram_write_clk ),
	// FIFO Read Side 1 (Leitura para o VGA)
	.RD1_DATA     ( SDRAM_RD_DATA[9:0] ),
	.RD1          ( READ_Request ),
	.RD1_ADDR     ( 0 ),
	.RD1_MAX_ADDR ( 640*480 ),
	.RD1_LENGTH   ( 256 ),
	.RD1_LOAD     ( !DLY_RST_1 ),
	.RD1_CLK      ( VGA_CLK ),
	// SDRAM Physical Side
	.SA           ( DRAM_ADDR ),
	.BA           ( DRAM_BA ),
	.CS_N         ( DRAM_CS_N ),
	.CKE          ( DRAM_CKE ),
	.RAS_N        ( DRAM_RAS_N ),
	.CAS_N        ( DRAM_CAS_N ),
	.WE_N         ( DRAM_WE_N ),
	.DQ           ( DRAM_DQ ),
	.DQM          ( DRAM_DQM )
);

assign RED   = SDRAM_RD_DATA[9:2];
assign GREEN = SDRAM_RD_DATA[9:2];
assign BLUE  = SDRAM_RD_DATA[9:2];

//------ VGA Controller ------
VGA_Controller u1 (
	.oRequest     ( READ_Request ),
	.iRed         ( RED ),
	.iGreen       ( GREEN ),
	.iBlue        ( BLUE ),
	.oVGA_R       ( R_AUTO[7:0] ),
	.oVGA_G       ( G_AUTO[7:0] ),
	.oVGA_B       ( B_AUTO[7:0] ),
	.oVGA_H_SYNC  ( VGA_HS ),
	.oVGA_V_SYNC  ( VGA_VS ),
	.oVGA_SYNC    ( VGA_SYNC_N ),
	.oVGA_BLANK   ( VGA_BLANK_N ),
	.iCLK         ( VGA_CLK ),
	.iRST_N       ( DLY_RST_2 ),
	.H_Cont       ( VGA_H_CNT ),
	.V_Cont       ( VGA_V_CNT )
);

// Connect design core to the camera driver & contour drawer
mnist_classifier_top APPLICATION_BLOCK (
	.VGA_CLK            ( VGA_CLK ),
	.RESET_N            ( DLY_RST_2 ),
	.VGA_HS             ( VGA_HS ),
	.VGA_VS             ( VGA_VS ),
	.CONTOUR_MODE       ( SW[0] ),
	.VGA_H_CNT          ( VGA_H_CNT ),
	.VGA_V_CNT          ( VGA_V_CNT ),
	.iVGA_R             ( R_AUTO ),
	.iVGA_G             ( G_AUTO ),
	.iVGA_B             ( B_AUTO ),
	.oVGA_R             ( processed_VGA_R ),
	.oVGA_G             ( processed_VGA_G ),
	.oVGA_B             ( processed_VGA_B ),
	.DIGIT_OUT          ( ),
	.HEX7               ( HEX7 ),
	.DIGIT_VALID_OUTPUT ( LEDG[0] ),
	.BOX_VALID          ( LEDG[1] )
);

assign LEDG[8:2] = 7'b0;

assign VGA_R = processed_VGA_R;
assign VGA_G = processed_VGA_G;
assign VGA_B = processed_VGA_B;

//------ VS FREQUENCY TEST = 60HZ --
FpsMonitor uFps(
	.clk50     ( CLOCK2_50 ),
	.vs        ( MIPI_PIXEL_VS ),
	.hex_fps_h ( HEX1 ),
	.hex_fps_l ( HEX0 )
);

//--LED DISPLAY DE DIAGNÓSTICO--
CLOCKMEM ck1 (
	.CLK      ( VGA_CLK ),
	.CLK_FREQ ( 25000000 ),
	.CK_1HZ   ( D8M_CK_HZ )
);

CLOCKMEM ck2 (
	.CLK      ( MIPI_REFCLK ),
	.CLK_FREQ ( 24000000 ),
	.CK_1HZ   ( D8M_CK_HZ2 )
);

CLOCKMEM ck3 (
	.CLK      ( MIPI_PIXEL_CLK ),
	.CLK_FREQ ( 25000000 ),
	.CK_1HZ   ( D8M_CK_HZ3 )
);

assign LEDR = { D8M_CK_HZ, D8M_CK_HZ2, D8M_CK_HZ3, 15'h0 };

endmodule
