/* As it shall pertain to a small portion of this design file: Copyright 2019, Grant Yu
Majority of the design file: Credits to Terasic and Terasic System Builder.
This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see [https://www.gnu.org/licenses/]. */

//=======================================================
//  This code is generated by Terasic System Builder
//  CORRIGIDO PARA MAPEAMENTO DE PINOS .QSF E TESTE SINTÉTICO INDEPENDENTE
//=======================================================

module DE2_115_D8M_RTL (

	//////////// CLOCK //////////
	input 		          		CLOCK2_50,
	input 		          		CLOCK3_50,
	input 		          		CLOCK_50,

	//////////// LED //////////
	output		     [8:0]		LEDG,
	output		    [17:0]		LEDR,

	//////////// KEY //////////
	input 		     [3:0]		KEY,

	//////////// SW //////////
	input 		    [17:0]		SW,

	//////////// SEG7 //////////
	output		     [6:0]		HEX0,
	output		     [6:0]		HEX1,
	output		     [6:0]		HEX2,
	output		     [6:0]		HEX3,
	output		     [6:0]		HEX4,
	output		     [6:0]		HEX5,
	output		     [6:0]		HEX6,
	output		     [6:0]		HEX7,

	//////////// VGA //////////
	output		          		VGA_BLANK_N,
	output		     [7:0]		VGA_B,
	output		          		VGA_CLK,
	output		     [7:0]		VGA_G,
	output		          		VGA_HS,
	output		     [7:0]		VGA_R,
	output		          		VGA_SYNC_N,
	output		          		VGA_VS,

	//////////// SDRAM //////////
	output		    [12:0]		DRAM_ADDR,
	output		     [1:0]		DRAM_BA,
	output		          		DRAM_CAS_N,
	output		          		DRAM_CKE,
	output		          		DRAM_CLK,
	output		          		DRAM_CS_N,
	inout 		    [31:0]		DRAM_DQ,
	output		     [3:0]		DRAM_DQM,
	output		          		DRAM_RAS_N,
	output		          		DRAM_WE_N,

	//////////// GPIO CONNECT TO CAMERA (NOMES EXATOS DO DE2_115_D8M_RTL.QSF) //////////
	inout 		          		CAMERA_I2C_SCL, // SCCB SIOC
	inout 		          		CAMERA_I2C_SDA, // SCCB SIOD
	output		          		CAMERA_PWDN_n,  // Power down (0 = ligado)
	output		          		MIPI_CS_n,
	inout 		          		MIPI_I2C_SCL,
	inout 		          		MIPI_I2C_SDA,
	output		          		MIPI_MCLK,
	input 		          		MIPI_PIXEL_CLK, // PCLK da Câmera
	input 		     [9:0]		MIPI_PIXEL_D,   // Dados da Câmera D[9:0]
	input 		          		MIPI_PIXEL_HS,  // HREF da Câmera
	input 		          		MIPI_PIXEL_VS,  // VSYNC da Câmera
	output		          		MIPI_REFCLK,    // XCLK enviado para a Câmera (24MHz)
	output		          		MIPI_RESET_n,   // Reset físico da Câmera
	output		     [6:0]		EX_IO
);

//=============================================================================
// REG/WIRE declarations
//=============================================================================
wire	[15:0]	SDRAM_RD_DATA;
wire			DLY_RST_0;
wire			DLY_RST_1;
wire			DLY_RST_2;
wire			SDRAM_CTRL_CLK;
wire			D8M_CK_HZ;
wire			D8M_CK_HZ2;
wire			D8M_CK_HZ3;

wire	[7:0]	RED;
wire	[7:0]	GREEN;
wire	[7:0]	BLUE;
wire	[12:0]	VGA_H_CNT;
wire	[12:0]	VGA_V_CNT;
wire			READ_Request;
wire	[7:0]	B_AUTO;
wire	[7:0]	G_AUTO;
wire	[7:0]	R_AUTO;
wire			RESET_N;

// Sinais intermediários do processador de imagem (APPLICATION_BLOCK)
wire	[7:0]	processed_VGA_R;
wire	[7:0]	processed_VGA_G;
wire	[7:0]	processed_VGA_B;

// Mapeamento dos pinos físicos para nomes amigáveis no código
wire        cmos_pclk  = MIPI_PIXEL_CLK;
wire        cmos_href  = MIPI_PIXEL_HS;
wire        cmos_vsync = MIPI_PIXEL_VS;
wire [7:0]  cmos_db    = SW[3] ? MIPI_PIXEL_D[9:2] : MIPI_PIXEL_D[7:0]; // Seleciona barramento via SW[3] se necessário

assign CAMERA_PWDN_n = 1'b0;    // Câmera sempre ativa
assign MIPI_CS_n     = 1'b0;
assign MIPI_RESET_n  = RESET_N; // Reset síncrono da câmera
assign MIPI_MCLK     = 1'b0;

//=======================================================
// Structural coding
//=======================================================

assign HEX2 = 7'h7F;
assign HEX3 = 7'h7F;
assign HEX4 = 7'h7F;
assign HEX5 = 7'h7F;
assign HEX6 = 7'h7F;
assign EX_IO = 7'b0;

//----- RESET RELAY --
RESET_DELAY u2 (	
	.iRST   ( KEY[0] ),
	.iCLK   ( CLOCK2_50 ),
	.oRST_0 ( DLY_RST_0 ),
	.oRST_1 ( DLY_RST_1 ),
	.oRST_2 ( DLY_RST_2 ),
	.oREADY ( RESET_N )
);

//------ OV7670 REF CLOCK (24 MHz fornecido ao pino MIPI_REFCLK) --
pll_test pll_ref(
	.inclk0 ( CLOCK3_50 ),
	.areset ( ~KEY[0] ),
	.c0     ( MIPI_REFCLK ) // Fornece 24 MHz no pino físico da câmera
);

//------ VGA REF CLOCK (25.18 MHz) --
VIDEO_PLL pll_ref1(
	.inclk0 ( CLOCK2_50 ),
	.areset ( ~KEY[0] ),
	.c0     ( VGA_CLK )   // 25.18 MHz para o VGA
);

//------ SDRAM CLOCK GENERATOR (100 MHz) --
sdram_pll u6(
	.areset ( 1'b0 ),
	.inclk0 ( CLOCK_50 ),
	.c1     ( DRAM_CLK ),       // 100MHZ -90 degree
	.c0     ( SDRAM_CTRL_CLK )  // 100MHZ 0 degree
);

//------ INSTANCIAÇÃO DO DRIVER DA CÂMERA OV7670 (INICIALIZADOR I2C/SCCB) ------
camera_interface camera_inst (
	.clk         ( CLOCK_50 ),
	.clk_100     ( SDRAM_CTRL_CLK ),
	.rst_n       ( RESET_N ),
	.key         ( KEY[3:0] ),
	.cmos_pclk   ( cmos_pclk ),
	.cmos_href   ( cmos_href ),
	.cmos_vsync  ( cmos_vsync ),
	.cmos_db     ( cmos_db ),
	.cmos_sda    ( CAMERA_I2C_SDA ),
	.cmos_scl    ( CAMERA_I2C_SCL ),
	.cmos_rst_n  ( ),
	.cmos_pwdn   ( ),
	.cmos_xclk   ( ),
	.rd_en       ( 1'b0 ),
	.dout        ( ),
	.data_count_r( ),
	.led         ( )
);

//=============================================================================
// CAPTURA DE PIXELS DA CÂMERA REAL (SINCRO PCLK)
//=============================================================================

reg [9:0] line_pixel_cnt;
reg [9:0] frame_line_cnt;
reg       byte_flag;
reg [7:0] msb_byte;
reg       cam_write_en;
reg [7:0] cam_gray;

reg href_d;
always @(posedge cmos_pclk or negedge RESET_N) begin
	if (~RESET_N) href_d <= 1'b0;
	else href_d <= cmos_href;
end

wire href_start = cmos_href & ~href_d;
wire href_end   = ~cmos_href & href_d;

always @(posedge cmos_pclk or negedge RESET_N) begin
	if (~RESET_N) begin
		line_pixel_cnt <= 10'd0;
		frame_line_cnt <= 10'd0;
		byte_flag      <= 1'b0;
		msb_byte       <= 8'h00;
		cam_write_en   <= 1'b0;
		cam_gray       <= 8'h00;
	end else if (cmos_vsync) begin
		line_pixel_cnt <= 10'd0;
		frame_line_cnt <= 10'd0;
		byte_flag      <= 1'b0;
		cam_write_en   <= 1'b0;
	end else if (href_start) begin
		line_pixel_cnt <= 10'd0;
		byte_flag      <= 1'b0;
		cam_write_en   <= 1'b0;
	end else if (cmos_href) begin
		if (byte_flag == 1'b0) begin
			msb_byte     <= cmos_db;
			byte_flag    <= 1'b1;
			cam_write_en <= 1'b0;
		end else begin
			byte_flag <= 1'b0;
			if (line_pixel_cnt < 10'd640 && frame_line_cnt < 10'd480) begin
				cam_write_en   <= 1'b1;
				line_pixel_cnt <= line_pixel_cnt + 1'b1;
				if (SW[2]) begin
					cam_gray <= msb_byte; // Modo YUV422
				end else begin
					cam_gray <= ({msb_byte[7:3], msb_byte[7:5]} * 306 + 
					             {msb_byte[2:0], cmos_db[7:5], msb_byte[2:1]} * 601 + 
					             {cmos_db[4:0], cmos_db[4:2]} * 117) >> 10;
				end
			end else begin
				cam_write_en <= 1'b0;
			end
		end
	end else begin
		cam_write_en <= 1'b0;
		if (href_end) begin
			if (frame_line_cnt < 10'd480)
				frame_line_cnt <= frame_line_cnt + 1'b1;
		end
	end
end

//=============================================================================
// GERADOR DE PADRÃO DE TESTE AUTÔNOMO SÍNCRONO COM VGA_CLK (ATIVADO VIA SW[1])
//=============================================================================

reg [9:0] test_x;
reg [9:0] test_y;
reg       test_write_en;
reg [7:0] test_gray;

always @(posedge VGA_CLK or negedge RESET_N) begin
	if (~RESET_N) begin
		test_x        <= 10'd0;
		test_y        <= 10'd0;
		test_write_en <= 1'b0;
		test_gray     <= 8'h00;
	end else if (SW[1]) begin
		test_write_en <= 1'b1;
		if (test_x < 10'd639) begin
			test_x <= test_x + 1'b1;
		end else begin
			test_x <= 10'd0;
			if (test_y < 10'd479)
				test_y <= test_y + 1'b1;
			else
				test_y <= 10'd0;
		end
		// Padrão de barras verticais / xadrez para teste de imagem limpa
		test_gray <= test_x[7:0] ^ test_y[7:0];
	end else begin
		test_write_en <= 1'b0;
		test_x        <= 10'd0;
		test_y        <= 10'd0;
	end
end

// SELEÇÃO FINAL DE GRAVAÇÃO NA SDRAM
wire        sdram_wr_clk  = (SW[1]) ? VGA_CLK : cmos_pclk;
wire        sdram_wr_en   = (SW[1]) ? test_write_en : cam_write_en;
wire  [7:0] sdram_wr_data = (SW[1]) ? test_gray : cam_gray;

//------ SDRAM CONTROLLER ------
Sdram_Control u7 (
	// HOST Side
	.RESET_N      ( KEY[0] ),
	.CLK          ( SDRAM_CTRL_CLK ),
	.WR1_DATA     ( {sdram_wr_data, 2'b00} ),
	.WR1          ( sdram_wr_en ),
	.WR1_ADDR     ( 0 ),
	.WR1_MAX_ADDR ( 640*480 ),
	.WR1_LENGTH   ( 256 ),
	.WR1_LOAD     ( !DLY_RST_0 ),
	.WR1_CLK      ( sdram_wr_clk ),
	// FIFO Read Side 1 (Leitura para o VGA)
	.RD1_DATA     ( SDRAM_RD_DATA[9:0] ),
	.RD1          ( READ_Request ),
	.RD1_ADDR     ( 0 ),
	.RD1_MAX_ADDR ( 640*480 ),
	.RD1_LENGTH   ( 256 ),
	.RD1_LOAD     ( !DLY_RST_1 ),
	.RD1_CLK      ( VGA_CLK ),
	// SDRAM Physical Side
	.SA           ( DRAM_ADDR ),
	.BA           ( DRAM_BA ),
	.CS_N         ( DRAM_CS_N ),
	.CKE          ( DRAM_CKE ),
	.RAS_N        ( DRAM_RAS_N ),
	.CAS_N        ( DRAM_CAS_N ),
	.WE_N         ( DRAM_WE_N ),
	.DQ           ( DRAM_DQ ),
	.DQM          ( DRAM_DQM )
);

assign RED   = SDRAM_RD_DATA[9:2];
assign GREEN = SDRAM_RD_DATA[9:2];
assign BLUE  = SDRAM_RD_DATA[9:2];

//------ VGA Controller ------
VGA_Controller u1 (
	.oRequest     ( READ_Request ),
	.iRed         ( RED ),
	.iGreen       ( GREEN ),
	.iBlue        ( BLUE ),
	.oVGA_R       ( R_AUTO[7:0] ),
	.oVGA_G       ( G_AUTO[7:0] ),
	.oVGA_B       ( B_AUTO[7:0] ),
	.oVGA_H_SYNC  ( VGA_HS ),
	.oVGA_V_SYNC  ( VGA_VS ),
	.oVGA_SYNC    ( VGA_SYNC_N ),
	.oVGA_BLANK   ( VGA_BLANK_N ),
	.iCLK         ( VGA_CLK ),
	.iRST_N       ( DLY_RST_2 ),
	.H_Cont       ( VGA_H_CNT ),
	.V_Cont       ( VGA_V_CNT )
);

// Connect design core to the camera driver & contour drawer
mnist_classifier_top APPLICATION_BLOCK (
	/////// INPUT VGA SIGNALS
	.VGA_CLK            ( VGA_CLK ),
	.RESET_N            ( DLY_RST_2 ),
	.VGA_HS             ( VGA_HS ),
	.VGA_VS             ( VGA_VS ),
	.CONTOUR_MODE       ( SW[0] ),           // SW[0] = Modo de Binarização/Contorno
	.VGA_H_CNT          ( VGA_H_CNT ),
	.VGA_V_CNT          ( VGA_V_CNT ),
	.iVGA_R             ( R_AUTO ),
	.iVGA_G             ( G_AUTO ),
	.iVGA_B             ( B_AUTO ),
	/////// OUTPUT VGA STREAM
	.oVGA_R             ( processed_VGA_R ),
	.oVGA_G             ( processed_VGA_G ),
	.oVGA_B             ( processed_VGA_B ),
	/////// TO 7 SEGMENT DISPLAY
	.DIGIT_OUT          ( ),
	.HEX7               ( HEX7 ),            // Exibe o dígito reconhecido no HEX7
	/////// LED OUTPUT
	.DIGIT_VALID_OUTPUT ( LEDG[0] ),
	.BOX_VALID          ( LEDG[1] )
);

assign LEDG[8:2] = 7'b0;

assign VGA_R = processed_VGA_R;
assign VGA_G = processed_VGA_G;
assign VGA_B = processed_VGA_B;

//------ VS FREQUENCY TEST = 60HZ --
FpsMonitor uFps(
	.clk50     ( CLOCK2_50 ),
	.vs        ( cmos_vsync ),
	.hex_fps_h ( HEX1 ),
	.hex_fps_l ( HEX0 )
);

//--LED DISPLAY--
CLOCKMEM ck1 (
	.CLK      ( VGA_CLK ),
	.CLK_FREQ ( 25000000 ),
	.CK_1HZ   ( D8M_CK_HZ )
);

CLOCKMEM ck2 (
	.CLK      ( MIPI_REFCLK ),
	.CLK_FREQ ( 24000000 ),
	.CK_1HZ   ( D8M_CK_HZ2 )
);

CLOCKMEM ck3 (
	.CLK      ( cmos_pclk ),
	.CLK_FREQ ( 25000000 ),
	.CK_1HZ   ( D8M_CK_HZ3 )
);

assign LEDR = { D8M_CK_HZ, D8M_CK_HZ2, D8M_CK_HZ3, 15'h0 };

endmodule
