library verilog;
use verilog.vl_types.all;
entity fmap_I is
    generic(
        ADDR_WIDTH      : integer := 8;
        DATA_WIDTH      : integer := 16;
        DEPTH           : integer := 196
    );
    port(
        clk             : in     vl_logic;
        wr_addr_1       : in     vl_logic_vector;
        wr_addr_2       : in     vl_logic_vector;
        wr_addr_3       : in     vl_logic_vector;
        wr_addr_4       : in     vl_logic_vector;
        wr_addr_5       : in     vl_logic_vector;
        wr_addr_6       : in     vl_logic_vector;
        wr_addr_7       : in     vl_logic_vector;
        wr_addr_8       : in     vl_logic_vector;
        wr_addr_9       : in     vl_logic_vector;
        wr_addr_10      : in     vl_logic_vector;
        wr_addr_11      : in     vl_logic_vector;
        wr_addr_12      : in     vl_logic_vector;
        wr_addr_13      : in     vl_logic_vector;
        wr_addr_14      : in     vl_logic_vector;
        wr_addr_15      : in     vl_logic_vector;
        wr_addr_16      : in     vl_logic_vector;
        rd_addr_1       : in     vl_logic_vector;
        rd_addr_2       : in     vl_logic_vector;
        rd_addr_3       : in     vl_logic_vector;
        rd_addr_4       : in     vl_logic_vector;
        rd_addr_5       : in     vl_logic_vector;
        rd_addr_6       : in     vl_logic_vector;
        rd_addr_7       : in     vl_logic_vector;
        rd_addr_8       : in     vl_logic_vector;
        rd_addr_9       : in     vl_logic_vector;
        rd_addr_10      : in     vl_logic_vector;
        rd_addr_11      : in     vl_logic_vector;
        rd_addr_12      : in     vl_logic_vector;
        rd_addr_13      : in     vl_logic_vector;
        rd_addr_14      : in     vl_logic_vector;
        rd_addr_15      : in     vl_logic_vector;
        rd_addr_16      : in     vl_logic_vector;
        wr_en_1         : in     vl_logic;
        wr_en_2         : in     vl_logic;
        wr_en_3         : in     vl_logic;
        wr_en_4         : in     vl_logic;
        wr_en_5         : in     vl_logic;
        wr_en_6         : in     vl_logic;
        wr_en_7         : in     vl_logic;
        wr_en_8         : in     vl_logic;
        wr_en_9         : in     vl_logic;
        wr_en_10        : in     vl_logic;
        wr_en_11        : in     vl_logic;
        wr_en_12        : in     vl_logic;
        wr_en_13        : in     vl_logic;
        wr_en_14        : in     vl_logic;
        wr_en_15        : in     vl_logic;
        wr_en_16        : in     vl_logic;
        wr_data_1       : in     vl_logic_vector;
        wr_data_2       : in     vl_logic_vector;
        wr_data_3       : in     vl_logic_vector;
        wr_data_4       : in     vl_logic_vector;
        wr_data_5       : in     vl_logic_vector;
        wr_data_6       : in     vl_logic_vector;
        wr_data_7       : in     vl_logic_vector;
        wr_data_8       : in     vl_logic_vector;
        wr_data_9       : in     vl_logic_vector;
        wr_data_10      : in     vl_logic_vector;
        wr_data_11      : in     vl_logic_vector;
        wr_data_12      : in     vl_logic_vector;
        wr_data_13      : in     vl_logic_vector;
        wr_data_14      : in     vl_logic_vector;
        wr_data_15      : in     vl_logic_vector;
        wr_data_16      : in     vl_logic_vector;
        rd_data_1       : out    vl_logic_vector;
        rd_data_2       : out    vl_logic_vector;
        rd_data_3       : out    vl_logic_vector;
        rd_data_4       : out    vl_logic_vector;
        rd_data_5       : out    vl_logic_vector;
        rd_data_6       : out    vl_logic_vector;
        rd_data_7       : out    vl_logic_vector;
        rd_data_8       : out    vl_logic_vector;
        rd_data_9       : out    vl_logic_vector;
        rd_data_10      : out    vl_logic_vector;
        rd_data_11      : out    vl_logic_vector;
        rd_data_12      : out    vl_logic_vector;
        rd_data_13      : out    vl_logic_vector;
        rd_data_14      : out    vl_logic_vector;
        rd_data_15      : out    vl_logic_vector;
        rd_data_16      : out    vl_logic_vector
    );
    attribute mti_svvh_generic_type : integer;
    attribute mti_svvh_generic_type of ADDR_WIDTH : constant is 1;
    attribute mti_svvh_generic_type of DATA_WIDTH : constant is 1;
    attribute mti_svvh_generic_type of DEPTH : constant is 1;
end fmap_I;
